// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using LeapDB;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class MenuSystemBase : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemUpdate {
        
        private IEcsComponentManagerOf<ExcerciseManagerComponent> _ExcerciseManagerComponentManager;
        
        private IEcsComponentManagerOf<EasyButton> _EasyButtonManager;
        
        private IEcsComponentManagerOf<IndexFingerComponent> _IndexFingerComponentManager;
        
        private IEcsComponentManagerOf<MediumButton> _MediumButtonManager;
        
        private IEcsComponentManagerOf<MenuButton> _MenuButtonManager;
        
        private IEcsComponentManagerOf<Difficulty> _DifficultyManager;
        
        private IEcsComponentManagerOf<MainButton> _MainButtonManager;
        
        private IEcsComponentManagerOf<HardButton> _HardButtonManager;
        
        private IEcsComponentManagerOf<HandComponent> _HandComponentManager;
        
        private IEcsComponentManagerOf<Easy> _EasyManager;
        
        private IEcsComponentManagerOf<Button> _ButtonManager;
        
        private IEcsComponentManagerOf<Hard> _HardManager;
        
        private IEcsComponentManagerOf<Menu> _MenuManager;
        
        private IEcsComponentManagerOf<Medium> _MediumManager;
        
        public IEcsComponentManagerOf<ExcerciseManagerComponent> ExcerciseManagerComponentManager {
            get {
                return _ExcerciseManagerComponentManager;
            }
            set {
                _ExcerciseManagerComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<EasyButton> EasyButtonManager {
            get {
                return _EasyButtonManager;
            }
            set {
                _EasyButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<IndexFingerComponent> IndexFingerComponentManager {
            get {
                return _IndexFingerComponentManager;
            }
            set {
                _IndexFingerComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MediumButton> MediumButtonManager {
            get {
                return _MediumButtonManager;
            }
            set {
                _MediumButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuButton> MenuButtonManager {
            get {
                return _MenuButtonManager;
            }
            set {
                _MenuButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Difficulty> DifficultyManager {
            get {
                return _DifficultyManager;
            }
            set {
                _DifficultyManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MainButton> MainButtonManager {
            get {
                return _MainButtonManager;
            }
            set {
                _MainButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<HardButton> HardButtonManager {
            get {
                return _HardButtonManager;
            }
            set {
                _HardButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<HandComponent> HandComponentManager {
            get {
                return _HandComponentManager;
            }
            set {
                _HandComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Easy> EasyManager {
            get {
                return _EasyManager;
            }
            set {
                _EasyManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Button> ButtonManager {
            get {
                return _ButtonManager;
            }
            set {
                _ButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Hard> HardManager {
            get {
                return _HardManager;
            }
            set {
                _HardManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Menu> MenuManager {
            get {
                return _MenuManager;
            }
            set {
                _MenuManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Medium> MediumManager {
            get {
                return _MediumManager;
            }
            set {
                _MediumManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            ExcerciseManagerComponentManager = ComponentSystem.RegisterComponent<ExcerciseManagerComponent>(34);
            EasyButtonManager = ComponentSystem.RegisterGroup<EasyButtonGroup,EasyButton>();
            IndexFingerComponentManager = ComponentSystem.RegisterComponent<IndexFingerComponent>(2);
            MediumButtonManager = ComponentSystem.RegisterGroup<MediumButtonGroup,MediumButton>();
            MenuButtonManager = ComponentSystem.RegisterGroup<MenuButtonGroup,MenuButton>();
            DifficultyManager = ComponentSystem.RegisterComponent<Difficulty>(31);
            MainButtonManager = ComponentSystem.RegisterComponent<MainButton>(30);
            HardButtonManager = ComponentSystem.RegisterGroup<HardButtonGroup,HardButton>();
            HandComponentManager = ComponentSystem.RegisterComponent<HandComponent>(1);
            EasyManager = ComponentSystem.RegisterComponent<Easy>(8);
            ButtonManager = ComponentSystem.RegisterComponent<Button>(7);
            HardManager = ComponentSystem.RegisterComponent<Hard>(11);
            MenuManager = ComponentSystem.RegisterComponent<Menu>(20);
            MediumManager = ComponentSystem.RegisterComponent<Medium>(10);
            this.OnEvent<uFrame.ECS.OnTriggerEnterDispatcher>().Subscribe(_=>{ MenuTriggerFilter(_); }).DisposeWith(this);
            this.OnEvent<LeapDB.ActivateMenu>().Subscribe(_=>{ ActiavateMenuEventFilter(_); }).DisposeWith(this);
            this.OnEvent<LeapDB.DeactivateMenu>().Subscribe(_=>{ DeactivateMenuEventFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void MenuTriggerHandler(uFrame.ECS.OnTriggerEnterDispatcher data, MenuButton collider, IndexFingerComponent source) {
            var handler = new MenuTriggerHandler();
            handler.System = this;
            handler.Event = data;
            handler.Collider = collider;
            handler.Source = source;
            handler.Execute();
        }
        
        protected void MenuTriggerFilter(uFrame.ECS.OnTriggerEnterDispatcher data) {
            var ColliderItem = MenuButtonManager[data.ColliderId];
            if (ColliderItem == null) {
                return;
            }
            if (!ColliderItem.Enabled) {
                return;
            }
            var SourceIndexFingerComponent = IndexFingerComponentManager[data.EntityId];
            if (SourceIndexFingerComponent == null) {
                return;
            }
            if (!SourceIndexFingerComponent.Enabled) {
                return;
            }
            this.MenuTriggerHandler(data, ColliderItem, SourceIndexFingerComponent);
        }
        
        protected virtual void ActiavateMenuEventHandler(LeapDB.ActivateMenu data, MenuButton group) {
            var handler = new ActiavateMenuEventHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void ActiavateMenuEventFilter(LeapDB.ActivateMenu data) {
            var MenuButtonItems = MenuButtonManager.Components;
            for (var MenuButtonIndex = 0
            ; MenuButtonIndex < MenuButtonItems.Count; MenuButtonIndex++
            ) {
                if (!MenuButtonItems[MenuButtonIndex].Enabled) {
                    continue;
                }
                this.ActiavateMenuEventHandler(data, MenuButtonItems[MenuButtonIndex]);
            }
        }
        
        protected virtual void DeactivateMenuEventHandler(LeapDB.DeactivateMenu data, MenuButton group) {
            var handler = new DeactivateMenuEventHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void DeactivateMenuEventFilter(LeapDB.DeactivateMenu data) {
            var MenuButtonItems = MenuButtonManager.Components;
            for (var MenuButtonIndex = 0
            ; MenuButtonIndex < MenuButtonItems.Count; MenuButtonIndex++
            ) {
                if (!MenuButtonItems[MenuButtonIndex].Enabled) {
                    continue;
                }
                this.DeactivateMenuEventHandler(data, MenuButtonItems[MenuButtonIndex]);
            }
        }
        
        protected virtual void MenuSystemUpdateHandler(MenuButton group) {
            var handler = new MenuSystemUpdateHandler();
            handler.System = this;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void MenuSystemUpdateFilter() {
            var MenuButtonItems = MenuButtonManager.Components;
            for (var MenuButtonIndex = 0
            ; MenuButtonIndex < MenuButtonItems.Count; MenuButtonIndex++
            ) {
                if (!MenuButtonItems[MenuButtonIndex].Enabled) {
                    continue;
                }
                this.MenuSystemUpdateHandler(MenuButtonItems[MenuButtonIndex]);
            }
        }
        
        public virtual void SystemUpdate() {
            MenuSystemUpdateFilter();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("e98c9fe3-d10e-4556-a42e-d311a7a7c6ae")]
    public partial class MenuSystem : MenuSystemBase {
        
        private static MenuSystem _Instance;
        
        public MenuSystem() {
            Instance = this;
        }
        
        public static MenuSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
