// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DeselectAllButtonsHandler {
        
        public MainButton Group;
        
        private LeapDB.DeselectMenuButtons _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool BoolNode263 = false;
        
        private UnityEngine.GameObject ActionNode264_obj = default( UnityEngine.GameObject );
        
        private string ActionNode264_color = default( System.String );
        
        private string StringNode265 = "white";
        
        private UnityEngine.GameObject ActionNode266_obj = default( UnityEngine.GameObject );
        
        private string ActionNode266_color = default( System.String );
        
        private UnityEngine.GameObject ActionNode267_obj = default( UnityEngine.GameObject );
        
        private string ActionNode267_color = default( System.String );
        
        public LeapDB.DeselectMenuButtons Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // SetVariableNode
            Group.easybutton.selected = (System.Boolean)BoolNode263;
            ActionNode264_obj = Group.easybutton.gameObject;
            ActionNode264_color = StringNode265;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode264_obj, ActionNode264_color);
            // SetVariableNode
            Group.mediumbutton.selected = (System.Boolean)BoolNode263;
            ActionNode266_obj = Group.mediumbutton.gameObject;
            ActionNode266_color = StringNode265;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode266_obj, ActionNode266_color);
            // SetVariableNode
            Group.hardbutton.selected = (System.Boolean)BoolNode263;
            ActionNode267_obj = Group.hardbutton.gameObject;
            ActionNode267_color = StringNode265;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode267_obj, ActionNode267_color);
        }
    }
}
