// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using LeapDB;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DifficultySystemEasyDifficultyHandler {
        
        public Difficulty Group;
        
        private LeapDB.EasyDifficulty _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode232_name = default( System.String );
        
        private string StringNode233 = "Difficulty";
        
        private UnityEngine.GameObject ActionNode232_result = default( UnityEngine.GameObject );
        
        private object ActionNode234_toCheck = default( System.Object );
        
        private LeapDB.Difficulty ActionNode241_component = default( LeapDB.Difficulty );
        
        private LeapDB.Difficulties ActionNode241_level = default( LeapDB.Difficulties );
        
        private string ActionNode241_type = default( System.String );
        
        private string StringNode242 = "easy";
        
        private LeapDB.Difficulties ActionNode379_level = default( LeapDB.Difficulties );
        
        private LeapDB.UpdateExcerciseScreen PublishEventNode380_Result = default( LeapDB.UpdateExcerciseScreen );
        
        public LeapDB.EasyDifficulty Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode232_name = StringNode233;
            // ActionNode
            // Visit GameObjectUtils.findGameObject
            GameObjectUtils.findGameObject(ActionNode232_name, out ActionNode232_result);
            ActionNode234_toCheck = ActionNode232_result;
            // ActionNode
            // Visit ConditionsUtils.isNull
            ConditionsUtils.isNull(ActionNode234_toCheck, ActionNode234_yes, ActionNode234_no);
        }
        
        private void ActionNode234_yes() {
        }
        
        private void ActionNode234_no() {
            ActionNode241_component = this.Group;
            ActionNode241_level = Group.level;
            ActionNode241_type = StringNode242;
            // ActionNode
            // Visit GameObjectUtils.setState
            GameObjectUtils.setState(ActionNode241_component, ActionNode241_level, ActionNode241_type);
            ActionNode379_level = Group.level;
            // ActionNode
            // Visit ExcerciseUtils.setDifficultyExcercises
            ExcerciseUtils.setDifficultyExcercises(ActionNode379_level);
            // PublishEventNode
            var PublishEventNode380_Event = new UpdateExcerciseScreen();
            System.Publish(PublishEventNode380_Event);
            PublishEventNode380_Result = PublishEventNode380_Event;
        }
    }
}
