// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DifficultySystemUpdateExcerciseScreenHandler {
        
        public ExcerciseManagerComponent Group;
        
        private LeapDB.UpdateExcerciseScreen _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode377_a = default( System.Int32 );
        
        private string ActionNode377_b = default( System.String );
        
        private string StringNode378 = ". Was ist...";
        
        private string ActionNode377_Result = default( System.String );
        
        public LeapDB.UpdateExcerciseScreen Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode377_a = Group.excerciseNr;
            ActionNode377_b = StringNode378;
            // ActionNode
            // Visit StringUtils.concatenateIntAndString
            ActionNode377_Result = StringUtils.concatenateIntAndString(ActionNode377_a, ActionNode377_b);
        }
    }
}
