// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using LeapDB;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DifficultySystemMediumDifficultyHandler {
        
        public Difficulty Group;
        
        private LeapDB.MediumDifficulty _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode243_name = default( System.String );
        
        private string StringNode244 = "Difficulty";
        
        private UnityEngine.GameObject ActionNode243_result = default( UnityEngine.GameObject );
        
        private object ActionNode247_toCheck = default( System.Object );
        
        private LeapDB.Difficulty ActionNode249_component = default( LeapDB.Difficulty );
        
        private LeapDB.Difficulties ActionNode249_level = default( LeapDB.Difficulties );
        
        private string ActionNode249_type = default( System.String );
        
        private string StringNode250 = "medium";
        
        private LeapDB.Difficulties ActionNode381_level = default( LeapDB.Difficulties );
        
        private LeapDB.UpdateExcerciseScreen PublishEventNode382_Result = default( LeapDB.UpdateExcerciseScreen );
        
        public LeapDB.MediumDifficulty Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode243_name = StringNode244;
            // ActionNode
            // Visit GameObjectUtils.findGameObject
            GameObjectUtils.findGameObject(ActionNode243_name, out ActionNode243_result);
            ActionNode247_toCheck = ActionNode243_result;
            // ActionNode
            // Visit ConditionsUtils.isNull
            ConditionsUtils.isNull(ActionNode247_toCheck, ActionNode247_yes, ActionNode247_no);
        }
        
        private void ActionNode247_yes() {
        }
        
        private void ActionNode247_no() {
            ActionNode249_component = this.Group;
            ActionNode249_level = Group.level;
            ActionNode249_type = StringNode250;
            // ActionNode
            // Visit GameObjectUtils.setState
            GameObjectUtils.setState(ActionNode249_component, ActionNode249_level, ActionNode249_type);
            ActionNode381_level = Group.level;
            // ActionNode
            // Visit ExcerciseUtils.setDifficultyExcercises
            ExcerciseUtils.setDifficultyExcercises(ActionNode381_level);
            // PublishEventNode
            var PublishEventNode382_Event = new UpdateExcerciseScreen();
            System.Publish(PublishEventNode382_Event);
            PublishEventNode382_Result = PublishEventNode382_Event;
        }
    }
}
