// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureSystemGameReadyHandler {
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode1_key = default( System.Object );
        
        private string StringNode2 = "AllExt";
        
        private bool ActionNode1_thumb = default( System.Boolean );
        
        private bool BoolNode3 = true;
        
        private bool ActionNode1_index = default( System.Boolean );
        
        private bool ActionNode1_middle = default( System.Boolean );
        
        private bool ActionNode1_fourth = default( System.Boolean );
        
        private bool ActionNode1_fifth = default( System.Boolean );
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode1_key = StringNode2;
            ActionNode1_thumb = BoolNode3;
            ActionNode1_index = BoolNode3;
            ActionNode1_middle = BoolNode3;
            ActionNode1_fourth = BoolNode3;
            ActionNode1_fifth = BoolNode3;
            // ActionNode
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode1_key, ActionNode1_thumb, ActionNode1_index, ActionNode1_middle, ActionNode1_fourth, ActionNode1_fifth);
        }
    }
}
