// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuTriggerHandler {
        
        public MenuButton Collider;
        
        public IndexFingerComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode168_value = default( System.Boolean );
        
        private LeapDB.DeactivateMenu PublishEventNode175_Result = default( LeapDB.DeactivateMenu );
        
        private LeapDB.ActivateMenu PublishEventNode66_Result = default( LeapDB.ActivateMenu );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode168_value = Collider.Button.selected;
            // ActionNode
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode168_value, ActionNode168_yes, ActionNode168_no);
        }
        
        private void ActionNode168_yes() {
            // PublishEventNode
            var PublishEventNode175_Event = new DeactivateMenu();
            System.Publish(PublishEventNode175_Event);
            PublishEventNode175_Result = PublishEventNode175_Event;
        }
        
        private void ActionNode168_no() {
            // PublishEventNode
            var PublishEventNode66_Event = new ActivateMenu();
            System.Publish(PublishEventNode66_Event);
            PublishEventNode66_Result = PublishEventNode66_Event;
        }
    }
}
