// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class NumberDetectionSystemGameReadyHandler {
        
        private uFrame.Kernel.KernelLoadedEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode315_key1 = default( System.Object );
        
        private int IntNode324 = 1;
        
        private string ActionNode315_question = default( System.String );
        
        private string StringNode325 = "4+4";
        
        private int ActionNode315_answer = default( System.Int32 );
        
        private int IntNode326 = 8;
        
        public uFrame.Kernel.KernelLoadedEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode315_key1 = IntNode324;
            ActionNode315_question = StringNode325;
            ActionNode315_answer = IntNode326;
            // ActionNode
            // Visit ExcerciseUtils.registerExcercise
            ExcerciseUtils.registerExcercise(ActionNode315_key1, ActionNode315_question, ActionNode315_answer);
        }
    }
}
