// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class NumberDetectionSystemFixedUpdateHandler {
        
        public ExcerciseManagerComponent Group;
        
        private uFrame.ECS.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode352_key = default( System.Object );
        
        private string ActionNode352_Result = default( System.String );
        
        private int ActionNode356_a = default( System.Int32 );
        
        private string ActionNode356_b = default( System.String );
        
        private string StringNode355 = ". Was ist...";
        
        private string ActionNode356_Result = default( System.String );
        
        public uFrame.ECS.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode352_key = Group.excerciseNr;
            // ActionNode
            // Visit ExcerciseUtils.getExcerciseText
            ActionNode352_Result = ExcerciseUtils.getExcerciseText(ActionNode352_key);
            // SetVariableNode
            Group.text.text = (System.String)ActionNode352_Result;
            ActionNode356_a = Group.excerciseNr;
            ActionNode356_b = StringNode355;
            // ActionNode
            // Visit StringUtils.concatenateIntAndString
            ActionNode356_Result = StringUtils.concatenateIntAndString(ActionNode356_a, ActionNode356_b);
            // SetVariableNode
            Group.title.text = (System.String)ActionNode356_Result;
        }
    }
}
