// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class NumberDetectionSystemRightAnswerHandler {
        
        public ExcerciseManagerComponent Group;
        
        private LeapDB.RightAnswer _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode337_message = default( System.Object );
        
        private string StringNode338 = "richtige Lösung!";
        
        private int ActionNode342_integer = default( System.Int32 );
        
        private int ActionNode342_Result = default( System.Int32 );
        
        private int ActionNode346_in = default( System.Int32 );
        
        private float ActionNode346_Result = default( System.Single );
        
        private float ActionNode345_a = default( System.Single );
        
        private int ActionNode347_in = default( System.Int32 );
        
        private float ActionNode347_Result = default( System.Single );
        
        private float ActionNode345_b = default( System.Single );
        
        private bool ActionNode345_Result = default( System.Boolean );
        
        private int IntNode349 = 1;
        
        public LeapDB.RightAnswer Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode337_message = StringNode338;
            // ActionNode
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode337_message);
            ActionNode342_integer = Group.excerciseNr;
            // ActionNode
            // Visit MathUtils.increment
            ActionNode342_Result = MathUtils.increment(ActionNode342_integer);
            // SetVariableNode
            Group.excerciseNr = (System.Int32)ActionNode342_Result;
            ActionNode346_in = ActionNode342_Result;
            // ActionNode
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode346_Result = uFrame.Actions.Converter.IntToFloat(ActionNode346_in);
            ActionNode345_a = ActionNode346_Result;
            ActionNode347_in = Group.maxExcercise;
            // ActionNode
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode347_Result = uFrame.Actions.Converter.IntToFloat(ActionNode347_in);
            ActionNode345_b = ActionNode347_Result;
            // ActionNode
            // Visit uFrame.Actions.Comparisons.GreaterThan
            ActionNode345_Result = uFrame.Actions.Comparisons.GreaterThan(ActionNode345_a, ActionNode345_b, ActionNode345_yes, ActionNode345_no);
        }
        
        private void ActionNode345_yes() {
            // SetVariableNode
            Group.excerciseNr = (System.Int32)IntNode349;
        }
        
        private void ActionNode345_no() {
        }
    }
}
