// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class TriggerEasyDifficultyHandler {
        
        public EasyButton Collider;
        
        public IndexFingerComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode130_value = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode133_obj = default( UnityEngine.GameObject );
        
        private string ActionNode133_color = default( System.String );
        
        private string StringNode134 = "white";
        
        private bool BoolNode136 = false;
        
        private LeapDB.DeselectMenuButtons PublishEventNode257_Result = default( LeapDB.DeselectMenuButtons );
        
        private UnityEngine.GameObject ActionNode118_obj = default( UnityEngine.GameObject );
        
        private string ActionNode118_color = default( System.String );
        
        private string StringNode119 = "green";
        
        private bool BoolNode132 = true;
        
        private LeapDB.EasyDifficulty PublishEventNode107_Result = default( LeapDB.EasyDifficulty );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode130_value = Collider.Button.selected;
            // ActionNode
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode130_value, ActionNode130_yes, ActionNode130_no);
        }
        
        private void ActionNode130_yes() {
            ActionNode133_obj = Collider.Button.gameObject;
            ActionNode133_color = StringNode134;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode133_obj, ActionNode133_color);
            // SetVariableNode
            Collider.Button.selected = (System.Boolean)BoolNode136;
        }
        
        private void ActionNode130_no() {
            // PublishEventNode
            var PublishEventNode257_Event = new DeselectMenuButtons();
            System.Publish(PublishEventNode257_Event);
            PublishEventNode257_Result = PublishEventNode257_Event;
            ActionNode118_obj = Collider.Button.gameObject;
            ActionNode118_color = StringNode119;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode118_obj, ActionNode118_color);
            // SetVariableNode
            Collider.Button.selected = (System.Boolean)BoolNode132;
            // PublishEventNode
            var PublishEventNode107_Event = new EasyDifficulty();
            System.Publish(PublishEventNode107_Event);
            PublishEventNode107_Result = PublishEventNode107_Event;
        }
    }
}
