// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class TriggerMediumDifficultyHandler {
        
        public MediumButton Collider;
        
        public IndexFingerComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode143_value = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode144_obj = default( UnityEngine.GameObject );
        
        private string ActionNode144_color = default( System.String );
        
        private string StringNode145 = "white";
        
        private bool BoolNode148 = false;
        
        private LeapDB.DeselectMenuButtons PublishEventNode268_Result = default( LeapDB.DeselectMenuButtons );
        
        private UnityEngine.GameObject ActionNode159_obj = default( UnityEngine.GameObject );
        
        private int ActionNode159_red = default( System.Int32 );
        
        private int IntNode160 = 255;
        
        private int ActionNode159_green = default( System.Int32 );
        
        private int IntNode161 = 0;
        
        private int ActionNode159_blue = default( System.Int32 );
        
        private int IntNode162 = 125;
        
        private bool BoolNode150 = true;
        
        private LeapDB.MediumDifficulty PublishEventNode37_Result = default( LeapDB.MediumDifficulty );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode143_value = Collider.Button.selected;
            // ActionNode
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode143_value, ActionNode143_yes, ActionNode143_no);
        }
        
        private void ActionNode143_yes() {
            ActionNode144_obj = Collider.Button.gameObject;
            ActionNode144_color = StringNode145;
            // ActionNode
            // Visit GameObjectUtils.setColor
            GameObjectUtils.setColor(ActionNode144_obj, ActionNode144_color);
            // SetVariableNode
            Collider.Button.selected = (System.Boolean)BoolNode148;
        }
        
        private void ActionNode143_no() {
            // PublishEventNode
            var PublishEventNode268_Event = new DeselectMenuButtons();
            System.Publish(PublishEventNode268_Event);
            PublishEventNode268_Result = PublishEventNode268_Event;
            ActionNode159_obj = Collider.Button.gameObject;
            ActionNode159_red = IntNode160;
            ActionNode159_green = IntNode161;
            ActionNode159_blue = IntNode162;
            // ActionNode
            // Visit GameObjectUtils.setColorRGB
            GameObjectUtils.setColorRGB(ActionNode159_obj, ActionNode159_red, ActionNode159_green, ActionNode159_blue);
            // SetVariableNode
            Collider.Button.selected = (System.Boolean)BoolNode150;
            // PublishEventNode
            var PublishEventNode37_Event = new MediumDifficulty();
            System.Publish(PublishEventNode37_Event);
            PublishEventNode37_Result = PublishEventNode37_Event;
        }
    }
}
