// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using Invert.Json;
    using LeapDB;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(31)]
    [uFrame.Attributes.uFrameIdentifier("b876dcf7-1d0d-4b72-84b3-c486e925dcd3")]
    public partial class Difficulty : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Difficulties _level;
        
        private Subject<PropertyChangedEvent<Difficulties>> _levelObservable;
        
        private PropertyChangedEvent<Difficulties> _levelEvent;
        
        public override int ComponentId {
            get {
                return 31;
            }
        }
        
        public IObservable<PropertyChangedEvent<Difficulties>> levelObservable {
            get {
                return _levelObservable ?? (_levelObservable = new Subject<PropertyChangedEvent<Difficulties>>());
            }
        }
        
        public Difficulties level {
            get {
                return _level;
            }
            set {
                Setlevel(value);
            }
        }
        
        public virtual void Setlevel(Difficulties value) {
            SetProperty(ref _level, value, ref _levelEvent, _levelObservable);
        }
    }
}
