// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(11)]
    [uFrame.Attributes.uFrameIdentifier("b75cd2b0-4682-448a-b928-17db1b98d45c")]
    public partial class Hard : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 11;
            }
        }
    }
}
