// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(20)]
    [uFrame.Attributes.uFrameIdentifier("be1ea832-f280-4226-8733-d20a95fb3bae")]
    public partial class Menu : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 20;
            }
        }
    }
}
