// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class EasyButtonGroup : ReactiveGroup<EasyButton> {
        
        private IEcsComponentManagerOf<Button> _ButtonManager;
        
        private IEcsComponentManagerOf<Easy> _EasyManager;
        
        private int lastEntityId;
        
        private Button Button;
        
        private Easy Easy;
        
        public IEcsComponentManagerOf<Button> ButtonManager {
            get {
                return _ButtonManager;
            }
            set {
                _ButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Easy> EasyManager {
            get {
                return _EasyManager;
            }
            set {
                _EasyManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            ButtonManager = componentSystem.RegisterComponent<Button>();
            yield return ButtonManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return ButtonManager.RemovedObservable.Select(_=>_.EntityId);;
            EasyManager = componentSystem.RegisterComponent<Easy>();
            yield return EasyManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return EasyManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((Button = ButtonManager[entityId]) == null) {
                return false;
            }
            if ((Easy = EasyManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override EasyButton Select() {
            var item = new EasyButton();;
            item.EntityId = lastEntityId;
            item.Button = Button;
            item.Easy = Easy;
            return item;
        }
    }
}
