// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(3)]
    public partial class HardButton : uFrame.ECS.GroupItem {
        
        private Hard _Hard;
        
        private Button _Button;
        
        public Hard Hard {
            get {
                return _Hard;
            }
            set {
                _Hard = value;
            }
        }
        
        public Button Button {
            get {
                return _Button;
            }
            set {
                _Button = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 3;
            }
        }
    }
}
