// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LeapDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class MediumButtonGroup : ReactiveGroup<MediumButton> {
        
        private IEcsComponentManagerOf<Button> _ButtonManager;
        
        private IEcsComponentManagerOf<Medium> _MediumManager;
        
        private int lastEntityId;
        
        private Button Button;
        
        private Medium Medium;
        
        public IEcsComponentManagerOf<Button> ButtonManager {
            get {
                return _ButtonManager;
            }
            set {
                _ButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Medium> MediumManager {
            get {
                return _MediumManager;
            }
            set {
                _MediumManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.IComponentSystem componentSystem) {
            ButtonManager = componentSystem.RegisterComponent<Button>();
            yield return ButtonManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return ButtonManager.RemovedObservable.Select(_=>_.EntityId);;
            MediumManager = componentSystem.RegisterComponent<Medium>();
            yield return MediumManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return MediumManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((Button = ButtonManager[entityId]) == null) {
                return false;
            }
            if ((Medium = MediumManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override MediumButton Select() {
            var item = new MediumButton();;
            item.EntityId = lastEntityId;
            item.Button = Button;
            item.Medium = Medium;
            return item;
        }
    }
}
